### ISSUE TITLE
Add Wallet Connect functionality to DWA Starter App Vue

### ISSUE THREAD

**Issue by blackgirlbytes** [TBD54566975/tbd-examples#149]
[placeholder for now]

**Comment by Johnnyevans32** [comment]
hi @blackgirlbytes, waiting to get more info on this so I can close it out

**Comment by blackgirlbytes** [comment]
Hey @Johnnyevans32 sorry about that, I was collecting information to distill for you from the engineering team. I haven't used the Wallet connect functionality myself, so I was hoping to read through the code. 

Here's the information I received so far:

- The regular OIDC/Wallet Connect flow is implemented here so they can look at this: [https://github.com/TBD54566975/tbd-examples/blob/4ee6c2e808efe28ae6529bd7b1396833b[…]5/javascript/dwa-starter-react-vite/src/web5/Web5Connection.tsx](https://github.com/TBD54566975/tbd-examples/blob/4ee6c2e808efe28ae6529bd7b1396833b729ffe5/javascript/dwa-starter-react-vite/src/web5/Web5Connection.tsx)
- They can use our react wallet or https://github.com/decentralized-identity/dweb-wallet to test their implementation.

But I'm planning to read through the code, so I can figure out the best way to write a description in a ticket for you. Hopefully, these links help for now!
