### ISSUE TITLE
pfi-aud-usd-tbdex error: Expected kid in JWS header to dereference to a DID Document Verification Method

### ISSUE THREAD

**Issue by finn-tbd** [TBD54566975/tbd-examples#24]
Running the `pfi-aud-usd-tbdex` example unmodified throws an error:

![image](https://github.com/TBD54566975/tbd-examples/assets/139806439/7e9a765e-f32a-4224-89df-6a5329d6c60b)

This issue was initially reported on [discord](https://discord.com/channels/937858703112155166/949067728709369856/1260996263449595965) and I was able to reproduce it by running the install/first run steps listed in the README.

**Comment by michaelneale** [comment]
fixed: https://github.com/TBD54566975/tbd-examples/pull/25

**Comment by michaelneale** [comment]
fixed
